version: '3.6'

services:
  powerbeatsvr:
    build:
        context: .
    container_name: powerbeatsvr
    restart: always
    tty: true
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=powerbeatsvr.gnethomelinux.com
      - LETSENCRYPT_HOST=powerbeatsvr.gnethomelinux.com
      - LETSENCRYPT_EMAIL=guysoft@gmail.com
    #entrypoint: /bin/sh

networks:
  default:
    external:
      name: nginx-proxy

